title: Hi, I'm Troy Swanson
description: The personal website of Troy Swanson
url: http://troyswanson.me

exclude: ["LICENSE.md", "README.md", "Dockerfile", "Gemfile", "Gemfile.lock", "vendor"]

plugins:
  - jekyll-seo-tag

compress_html:
  startings: all
  endings: all
  comments: all
